server:
  port: 9000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/authorization
    username: postgres
    password: postgres
  liquibase:
    driver-class-name: org.postgresql.Driver
    change-log: classpath:/db/db.changeLog-master.yml
  jpa:
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000