version: "3.7"

services:
  postgres:
    image: postgres:14.1
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - D:/docker/storage/postgres:/var/lib/postgres
    environment:
      POSTGRES_DB: entities
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  pg-admin:
    image: dpage/pgadmin4:6.8
    container_name: pg-admin
    ports:
        - '5050:80'
    environment:
        PGADMIN_DEFAULT_EMAIL: test@gmail.com
        PGADMIN_DEFAULT_PASSWORD: postgres