server:
  port: 8090

spring:
  datasource:
    authorization:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://host.docker.internal:5430/authorization
      username: postgres
      password: postgres
      liquibase:
        driver-class-name: org.postgresql.Driver
        change-log: classpath:/db/db.authorization.changeLog-master.yml
    giftcertificates:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://host.docker.internal:5432/giftcertificates
      username: postgres
      password: postgres
      liquibase:
        driver-class-name: org.postgresql.Driver
        change-log: classpath:/db/db.giftcertificates.changeLog-master.yml
  jackson:
    serialization:
      write_dates_as_timestamps: false
  jpa:
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE