version: "3.8"

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: coupons-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: coupons
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres